### ISSUE TITLE
python 3.12 required?

### ISSUE THREAD

**Issue by ghost** [phi-friday/diskcache-stubs#2]
Hi, thanks for writing stubs for diskcache :).

The project declares compatibility with python 3.8 (?) but installing it into a python 3.11 venv and trying to run mypy results in syntax errors:

```
venv/lib/python3.11/site-packages/diskcache-stubs/core.pyi:58: error: invalid syntax  [syntax]
```

You should probably declare this  compatible only with python 3.12+

**Comment by phi-friday** [comment]
First of all, I only use pyright (pylance to be exact), so I don't check for mypy (I don't know how to use it, let me know and I'll adapt).

When I checked where the error occurred, I got the following code.
```python
class Constant[T: str](tuple[T]):  # noqa: SLOT001
    def __new__(cls, name: T) -> Self: ...
```

It's definitely a syntax that's supported since 3.12, and I thought that if it was a stub file, it would work regardless of version.
This is not what I intended.
I'll fix it soon.

However, as I said before, it's hard to verify using mypy, so it may not work with mypy.

**Comment by phi-friday** [comment]
@BubuOT 
Removed the part where PEP 695 was applied.
For now, it seems to work fine in my environment (3.8.16, pylance), but I'd like to check it on mypy.
Can you confirm this for me, or share how to set it up?

**Comment by ghost** [comment]
@phi-friday Thanks, installing this from `main` now works with mypy for me :).

As for how to set it up, it should just be installing mypy via pip and then running `mypy --strict .` on a codebase using diskcache (and with the stubs installed).

**Comment by phi-friday** [comment]
First, I added mypy to development dependencies.

After checking a bit more, it seems to be a problem with mypy only.
This seems to be causing a number of issues, so I disabled the following error codes
`valid-type,type-arg,overload-overlap,misc,operator`
If I were to set the covariances myself, this might work, but I don't think it's necessary right now.

I don't use mypy much, so there's a lot I don't know about it, so please forgive me.
I'll close this issue with the new release `5.6.3.4`

**Comment by ghost** [comment]
With "works with mypy" I mostly meant that it's no longer having syntax problems. I suppose there's more things on the actual types that might need to be changed.

I specifically want to get the typing of the `@cache.memoize()` decorator working (with mypy), I'll make a PR, if I get it to work :).

**Comment by phi-friday** [comment]
@BubuOT 
I removed the parameter type of `__cache_key__` and changed the definition of `Memoized`. 
(The parameter type of `__cache_key__` is important, but I decided that it was more important to have it work in mypy.)

Can you confirm that it works?
